### ISSUE TITLE
'Symbol.iterator' is not defined on some browsers

### ISSUE THREAD

**Issue by AndreiZavidei** [TranscryptOrg/Transcrypt#298]
Hi,

Transcrypt uses 'Symbol.iterator' when it generates code for Python dict implementation:

**Javascript code:**
`__setProperty__ (instance, Symbol.iterator, {value: function () {new __JsIterator__ (this.py_keys ());}, enumerable: false});`

On some native mobile browsers (e.g. tested on Galaxy S4 mini) 'Symbol' is not defined as built-in JS object and code above gives TypeError.

My question is: can this functionality be somehow disabled if user does not need iterator support?

Thanks!

**Comment by JdeH** [comment]
Hi, an experimental fix has been commited for this, namely the --ext_noiter / -xni switch.
As I don't have a suitable browser myself, I've no idea if this actually covers all relevant occurences of Symbol.iterator.

Note that JS6 support and, in general, iterator support will be absent in the generated code.

**Comment by AndreiZavidei** [comment]
Hi,

Sorry for late reply. 
My Samsung s4 mini not always connects to remote debugger. So I could not see the console output, but I tested the fix, unfortunately, it did not help (or maybe some other problem appeared).
Please give me some time, I will investigate if problem can be solved with 'core-js' package. Maybe your fix won't be necessary.

Thanks!

**Comment by JdeH** [comment]
OK,

Thanks for the effort, keep me informed.

KR
Jacques

**Comment by JdeH** [comment]
I'll close this for now, since it is probably not going to be solved in Transcrypt itself. But I am still curious if the workaround with core-js solves this backward compatibility problem.

**Comment by amiguet** [comment]
Hi,

I also encountered this problem (on a ZTE open C with firefox OS) and wanted to report that a simple
`<script src="https://raw.githack.com/zloirock/core-js/v2.5.0/client/shim.min.js"></script>`
works for me.

Cheers,

Matthieu

**Comment by geatec** [comment]
Thanks for reporting this!

**Comment by JdeH** [comment]
Thanks for reporting this problem and the workaround!

**Comment by classifaddict** [comment]
Hi,
This is happening to me now with IE 11.0.9600.18762, Transcrypt==3.6.47 and with or without -xni switch.
But the workaround indicated by Matthieu seems to be good.

**Comment by JdeH** [comment]
The workaround deserves a place in the docs.

**Comment by JennaSys** [comment]
Not sure this is relevant any longer - closing for now.
