### ISSUE TITLE
Add key= support for max() function

### ISSUE THREAD

**Issue by Levtastic** [TranscryptOrg/Transcrypt#305]
In python, you can add a function to a call to `max()` using the `key=` keyword arg, which lets you do more complex logic for finding the value you want, but in Transcrypt it looks like `max()` is mapped directly to `Math.max()` and so doesn't have this ability.

**Comment by Levtastic** [comment]
If this is added, I'd like to also request that it be added to functions like [sorted()](https://docs.python.org/3.6/library/functions.html#sorted) too, as I also use it in that situation a lot, as well as min()/max()

**Comment by JennaSys** [comment]
Added in dev_3.9.3 branch to be released in v3.9.3

**Comment by JennaSys** [comment]
Merged to master on PR #876
