### ISSUE TITLE
Mixing Python and Native JS Code

### ISSUE THREAD

**Issue by notzoom** [TranscryptOrg/Transcrypt#487]
I would like to ask, to what extend we can do that ? 

What is allowed in terms of putting some Native JS code and what not ? 

I have tried to put a few things that were requiring special Transcrypt Syntax.

Is that a good thing since the beginner will very often like to just paste JS snippets they find on the web ?

**Comment by JdeH** [comment]
You can mix in any JavaScript with `__pragma__ ('js'...`, even complete libraries.
In the example below, the complete fabric.js is included! There aren't any restrictions to this.

http://www.transcrypt.org/docs/html/integration_javascript.html#code-encaps-fabric

**Comment by notzoom** [comment]
@JdeH I am not sure I understand how this is done. For instance, say I have this snippet:
var name = "codemzy";
$.get('https://www.freecodecamp.com/' + name, function(response) {
  console.log(response);
});
And I want to put it as is, how will I do that ? Thanks.

**Comment by JdeH** [comment]
Just insert:

'''
__pragma__ ('js', '{}'. '''
    $.get('https://www.freecodecamp.com/' + name, function(response) {
    console.log(response);
});
'''

**Comment by notzoom** [comment]
@JdeH Oh wow, it's that simple ? That is awesome !!! Thanks a lot Jacques.

**Comment by JdeH** [comment]
you're welcome!

**Comment by notzoom** [comment]
@JdeH And that goes to whatever necessary point in the code and executed normally without any additional steps, right ?

**Comment by JdeH** [comment]
Right!

**Comment by neriusmika** [comment]
BTW that code could be implemented in python like this:
```python
__pragma__ ('alias', 'S', '$')
name = 'codemzy'
S.js_get('https://www.freecodecamp.com/' + name, lambda response: console.log(response))
```

**Comment by JdeH** [comment]
That's even better...
Thanks @neriusmika
