### ISSUE TITLE
Symbolic Calculation's Possible?

### ISSUE THREAD

**Issue by CesMak** [TranscryptOrg/Transcrypt#490]
Hey,

I would like to also do some symbolic calculations. 

I would like to do something like this: det(s*I-A) with I unity matrix and A nxn real Matrix and s a symbol.

Currently I used Algebrite which could do that..... But now I switched to transcrypt and I find no solution how to do that so far ...... 

Does anyone know's a workaround of this problem

**Comment by neriusmika** [comment]
In Transcrypt almost all operators are overloadable, so you can use your own types and overload operators. Read the docs about opov pragma and look at the examples (e.g. complex type).

**Comment by CesMak** [comment]
Hey,
I just checked the documentation. I understand how to use the complex type:
```
        __pragma__('opov')
        a = 234 + 3j
        b = 4 - 5j
        print(b)
        c = complex(-6, 7)
        print(c)
        d = 1
        print(d.conjugate().real)
        print(d.conjugate().imag)
        __pragma__('noopov')
```
This just works fine for me. But I do not get it how to overload parameters to use symbols....

I would be really happy if you could write a minimal example to solve the above problem for instance det(lambda I - A)

**Comment by neriusmika** [comment]
You must write \_\_sub\_\_ method for your type like in CPython and do what you want. Read about operator overloading in python. The difference is only that you need opov pragma in Transcrypt.

**Comment by neriusmika** [comment]
For example subtraction in Transcrypt complex type is implemented like this:
```python
def __sub__ (self, other):
    if __typeof__ (other) is 'number':
        return complex (self.real - other, self.imag)
    else:
        return complex (self.real - other.real, self.imag - other.imag)
```

**Comment by CesMak** [comment]
Äh ok sry if my question is to simple for you.....

So If I would like to calculate with symbols as well, Do I have to of complement all the funkctions __sub__ , __add__ etc. to use all these functions also in a symbolic way?

**Comment by neriusmika** [comment]
Yes, you need to overload all operations that you use with your own type if they must act differently from the standard types. As a starting point look at the complex implementation in transcrypt/modules/org/transcrypt/\_\_standard\_\_.py

**Comment by CesMak** [comment]
Hey thanks for that great tipps! 

I got it to work in a way like this:

`from org.transcrypt.stubs.browser import *
from org.transcrypt.stubs.browser import __main__, __envir__, __pragma__
from itertools import chain
from math import *

# Imports for Transcrypt, skipped runtime by CPython
if __envir__.executor_name == __envir__.transpiler_name:
	import numscrypt as num

# Imports for CPython, skipped compile time by Transcrypt
__pragma__ ('skip')
import numpy as num  # -> list of functions: https://transcrypt.org/numscrypt/docs/html/supported_constructs.html
__pragma__ ('noskip')


class Symbolic:
    def __init__(self, numeric_value, symblic_value=''):
        print(numeric_value)
        self.numeric_value = numeric_value
        self.symblic_value = self.convert_to_no_s(symblic_value)

    def convert_to_no_s(self, input_value):
        # input_value ex.: '10s'
        input_value = input_value.replace(" ", "")
        if input_value == "s":
            input_value = "1"
        else:
            input_value = input_value.replace("s", "")
        return input_value

    def __add__(self, other):
        tmp1 = float(self.numeric_value) + float(other.numeric_value)
        tmp2 = float(self.symblic_value) + float(other.symblic_value)
        print(tmp1)
        print(tmp2)
        return str(tmp1) + "+" + str(tmp2) + "s"

    def __mul__(self, other):
        tmp1 = float(self.numeric_value) * float(other.numeric_value)
        tmp2 = float(self.symblic_value) * float(other.symblic_value)
        return str(tmp1) + "*" + str(tmp2) + "s"

    def __str__(self):
        return str(self.numeric_value) + self.symblic_value

#simactBasic = SimactBasic()
a = Symbolic('2', '4s')
b = Symbolic('5', '8s')
__pragma__('opov')
c = a + b
__pragma__('noopov')
print(c)
print(eval('a+b'))`

Now the last line of code actually works in plain python. But not with transcrypt :( 

That brings me to my next question: Is there a posability to evaluate string expressions in transcrypt? 
For instance I read in do the following commands:
a=Symbolic('2', '4s')  that should store me a symbolic value in my local storage
next in my input window I would like to calculate  'a+a' but I have no idea how to do that cause I first have to replace all a or create objects for it? and next I need to evaluate this string.....

**Comment by JdeH** [comment]
You can  just use javaScript's `eval` function as described at #491

**Comment by JennaSys** [comment]
Closing as answered
