### ISSUE TITLE
Phaser Game Framework

### ISSUE THREAD

**Issue by notzoom** [TranscryptOrg/Transcrypt#492]
So I begun using this recently (without using Transcrypt) and it's mind blowing what games you can create in just a few lines of code. Extremely beginner friendly. I think Transcrypt would benefit immensely if there was a tutorial about writing Phaser games with it. Just wanted to bring this to the attention of Jacques and whoever may be interested.

**Comment by JdeH** [comment]
Games are popular and examples of Phaser games are of course welcome as contributions in the gallery.
With regard to Transcrypt I have to limit myself to the core (apart from the Pong example :) ).

**Comment by fzzylogic** [comment]
@notzoom, I did a [direct conversion](https://github.com/fzzylogic/phaser3_transcrypt_tutorial) of the Phaser 3 intro tutorial. Left the 'this' keywords in, i guess not all would be pleased with that, but at least it demonstrates that it's not a very big jump to get started.

**Comment by notzoom** [comment]
@fzzylogic That is totally fantastic !!! Well done !!!!

**Comment by fzzylogic** [comment]
@notzoom, Thanks. It would be more interesting if it took advantage of python specific language features. So be sure to share your creations!

**Comment by JennaSys** [comment]
Closing since no further comments for a while now.
