### ISSUE TITLE
Dual plugins for PyCharm and WebStorm

### ISSUE THREAD

**Issue by kiwi0fruit** [TranscryptOrg/Transcrypt#553]
It would be nice to have dual plugins for PyCharm and WebStorm that autotranspile, read warnings and errors from WebStorm then map them to the piece of python code in PyCharm, highlight and display.

Such checks can be made manually but such automation would be convenient.

**Comment by JennaSys** [comment]
I actually have a personal bulletpoint list of what I would like to see in a Transcrypt plug-in for PyCharm, and have considered creating one. The plug-in would likely have to be created using Kotlin and from what I've seen, the PyCharm plug-in architecture has a bit of a learning curve. Regardless though, it would have to be done as a separate project from Transcrypt itself.
