### ISSUE TITLE
Pyodide Integration

### ISSUE THREAD

**Issue by Immortalin** [TranscryptOrg/Transcrypt#571]
It would potentially allow full access to the Python Scientific Stack.

**Comment by JennaSys** [comment]
I think that Pyodide and Transcrypt both solve similar problems, but approach it from different directions. They certainly both have valid applications depending on what needs to be accomplished. While having access to the Python Scientific Stack would be nice, integration with Pyodide kind of goes against the grain of how Transcrypt was designed to be used.
