### ISSUE TITLE
Vue.js export

### ISSUE THREAD

**Issue by avosirenfal** [TranscryptOrg/Transcrypt#610]
I'm trying to get vue.js [Single File Components](https://vuejs.org/v2/guide/single-file-components.html) to run under the vue-cli environment.

I've written a Webpack loader that can transcrypt SFCs, but I have a problem - I can't control how Transcrypt does Javascript exports.

To get the build pipeline to run properly I _must_ export the component as part of `export default`, like so-

```python
class HelloWorld:
	def data(self):
		return {'count': 0}

__pragma__('js', """
export default {
	components: {
		HelloWorld: HelloWorld,
	},
}
""")
```

`__pragma('js', ...)` silently fails if you have `export default` or `module.exports` within it. I'm not sure if this is intended behavior.

I can work around this by putting the Python code in a separate file, and then importing it with JavaScript in the `.vue` instead-

```javascript
import HelloWorld from '../test.py';

export default {
	components: {
		HelloWorld: HelloWorld,
	},
}
```

This _does_ work, but it's obviously messy and unpleasant to do.

**Comment by avosirenfal** [comment]
Actually, this silently fails (there's nothing in the output file where the pragma was) too-

```python
__pragma__('js', "let test = {'count': 0};")
__pragma__('js', "console.log('test');")
```

The first line doesn't appear, the `console.log` line does. Am I missing something?

**Comment by avosirenfal** [comment]
Switched to Javascripthon instead for the moment.

**Comment by AlexECX** [comment]
Use this instead:
```
__pragma__('js', '{}', """
export default {
	components: {
		HelloWorld: HelloWorld,
	},
}
""")
```
Using text that has brackets in it will fail if used in the second parameter, as it is used for string formating and `{}` is reserved (like in `"My {} is {}".format("name", "Peter")`)

**Comment by JdeH** [comment]
@avosirenfal Does this solution work for you?
@AlexECX Thanks!

**Comment by Andrei-Pozolotin** [comment]
related:
https://github.com/QQuick/Transcrypt/issues/665

**Comment by Shu-Ji** [comment]
This worked for me:

// App.vue
```vue
<template lang="pug">
    div
        button {{ msg }}
</template>

<script>
    export default require('./app.py').HelloWorld()
</script>
```

# app.py
```python
class HelloWorld:
    js_name = 'HelloWorld'   # vue component name

    def data(self):
        return {
            'msg': 'Hello World From Python!'
        }
```

**Comment by JennaSys** [comment]
Closing since there have been no further comments for a while.
