### ISSUE TITLE
Output dir __target__/  could be renamed

### ISSUE THREAD

**Issue by berinhard** [TranscryptOrg/Transcrypt#628]
Hi! I've been using trancrypt to access P5.js lib from Python and it's been awesome! Congratulations for the good job on this project! I think I have a feature suggestion I'd like to share with you.

I'm having some issues with Github.io using the compiled js files from the default `__target__` directory. If you want more details about that, you can go to [this issue](https://github.com/berinhard/pyp5js/issues/1) and also this [fix commit](https://github.com/berinhard/sketches/commit/4545779b9ed0d013222762a0aff86443b3b75874). But the short story is I'm having rename the directory from `__target__`  to `target` to be able to properly access the compiled files. I don't know why, but it's probably something with Github's URL...

Anyway, I took a look at the code and noticed the `__target__` dir is hardcoded as a string in [`transcrypt/modules/org/transcrypt/compiler.py`](https://github.com/QQuick/Transcrypt/blob/master/transcrypt/modules/org/transcrypt/compiler.py#L75) and [`transcrypt/modules/org/transcrypt/autotester/html.py`](https://github.com/QQuick/Transcrypt/blob/master/transcrypt/modules/org/transcrypt/autotester/html.py) files.

I was wondering if there's a way to add a flag to the `trancrypt` command to customize this directory name. For now I'm renaming this directory from my own script, but I guess this could be a nice thing to have available in the command line interface as well. What do you think about that?

Thanks :+1:

**Comment by JdeH** [comment]
Thanks for the practical suggestion. The switch will be there in the next minor version.

**Comment by Andrei-Pozolotin** [comment]
also
https://github.com/QQuick/Transcrypt/issues/675

**Comment by JennaSys** [comment]
As of version 3.9.0, Transcrypt now has the `--outdir` [command line parameter](--outdir) that lets you optionally specify the build folder.
