### ISSUE TITLE
Concurrency + EuroPython

### ISSUE THREAD

**Issue by PythonLinks** [TranscryptOrg/Transcrypt#647]
As far as I can tell, Transcrypt supports concurrent WebWorkers.  In contrast to cPython which can only run 1 thread at a time.  cPython's promised subInterpreters have been delayed until Python 3.9.  I am not confident we will even see them then.  I  would think that Transcrypt's concurrent execution of Python Web Workers  would be a huge advantage for Transcrypt. Am I correct?  What should I be saying about this at EuroPython.

Is anyone else going to EuroPython?  Is anyone going to be doing a lightning talk about Transcrypt.  Sadly my one lightnig talk will be about the 12 best lightning talks at PyCon USA. 
https://pythonlinks.info/the-best-lightning-talks-of-pycon-usa-2019

I wonder if there will be a transcrypt sprint?

**Comment by JdeH** [comment]
Sorry for the late reaction.
See my answer to #646

**Comment by JennaSys** [comment]
Closing since there have been no further comments for a while.
