### ISSUE TITLE
Possible optimizations and improvements

### ISSUE THREAD

**Issue by DonaldTsang** [TranscryptOrg/Transcrypt#652]
- [ ] Rallying people to get the JS port to work
  - [ ] Get on the front pages of tech magazines
  - [ ] Start a crowd fund or feature bounty programme
- [ ] Get the SciPy stack working on transcrypt (scientific calculation without JS)
  - [ ] NumPy (the base array library for everything)
  - [ ] SciPy and SymPy (mathematics and scientific calculations)
  - [ ] Matplotlib (for graphing complex data)
  - [ ] Pandas (complex data structures and tables)
  - [ ] IPython and Jupyter (interactivity)
  - [ ] nose (user notes and documentation)
  - [ ] (other items in https://github.com/iodide-project/pyodide)
- [ ] Get Cython optimizations to actually work (in order to get some packages to work)
- [ ] (Possibly a non-Python to WebAssembly builder (to covert all packages))

**Comment by JdeH** [comment]
That's quite a list...
Getting on the front page of tech magazines only succeeded with Linux Journal. There'a a lot happening and the fight for attention isn't easy. Any help appreciated.

About the crowd fund: The first step would be to put the whole thing into a foundation, juridically distinct from my person. Continuity is very important for trust and mindshare, so at some time that probably will have to happen. Before attracting significant funds there will have to be a solid, accountable organisation one way or the other. Having said that, there are some financial contributions coming in currently, which make it possible to devote some of my working time to Transcrypt.

About Numpy etc.: There's a companion project https://github.com/QQuick/Numscrypt that covers some of it's functionality. But fully supporting the CPython scientific stack currently can't be done without introducing large page load times. A choice had to be made here. As long as browsers don't support native machine language, compiled from C++, large amounts of memory and unimpeded disk access, computing in the browser will be no match for computing on the server. Still Numscrypt can do some nice tricks, like matrix-vector algebra with operator overloading, 1D and 2D real and complex FFT and eigenvalue problems. But it's currently rather a well kept secret...

**Comment by DonaldTsang** [comment]
About the first two, that is something we have to work on human-resources wise.
The last however, I do believe that the stack needs to be made such that C++ and WebAssembly would be the most open to analysis or reverse engineer, or at worst the stack needs to AVOID WA by relying on massive amounts of NPM libraries (of course forks and not the original dependency due to deletion issues) to cheat the system and make it easy to write a whole stack.
