### ISSUE TITLE
Error when compiling python class

### ISSUE THREAD

**Issue by BannerBomb** [TranscryptOrg/Transcrypt#662]
```js
bannerbomb@bannerbomb-HP-G71-Notebook-PC:~/Desktop/test_trans$ transcrypt -v -b -n -p .none __init__.py

Transcrypt (TM) Python to JavaScript Small Sane Subset Transpiler Version 3.7.16
Copyright (C) Geatec Engineering. License: Apache 2.0


Parsing module: /usr/local/lib/python3.7/site-packages/transcrypt/modules/org/transcrypt/__runtime__.py
Generating code for module: /home/bannerbomb/Desktop/test_trans/__target__/org.transcrypt.__runtime__.js
Saving target code in: /home/bannerbomb/Desktop/test_trans/__target__/org.transcrypt.__runtime__.js
Parsing module: /home/bannerbomb/Desktop/test_trans/__init__.py
Generating code for module: /home/bannerbomb/Desktop/test_trans/__target__/__init__.js

Error while compiling (offending file last):
	File '__init__', line 103, namely:
	
	Error while compiling (offending file last):
	File '__init__', line 103, namely:
	

Aborted
```

I am messing around with different scripts and I tried this script [here](https://github.com/python/cpython/blob/3.7/Lib/collections/__init__.py) and the above error is what I got after using transcrypt as follows `transcrypt -v -n -b -p .none __init__.py`. My computer type is Ubuntu 18.04.2 and my python version is `Python 3.7.4`, I have installed transcrypt using `sudo pip3 install transcrypt`

**Comment by AlexECX** [comment]
If I understand correctly, based on the link provided, this is a module from the collections package. Unfortunately, packages from the python standard library, as well as third party packages that use them, are generally not compilable with transcrypt. A [few modules](http://www.transcrypt.org/docs/html/supported_constructs.html#module-builtin-a-small-part-of-it-demo-ed) have been ported, partially or in there entirety.

**Comment by JdeH** [comment]
Ported modules (partially or as a whole) are in Transcrypt's modules directory.
In general, Transcrypt relies on JS libraries.
But the collections package would be useful to add.

**Comment by JennaSys** [comment]
Closing  - implementing the collections module is covered on issue #442
