### ISSUE TITLE
FR: compiler source vs target separation

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [TranscryptOrg/Transcrypt#675]
1. currently compiler output is hard coded [compiler.py#L75](https://github.com/QQuick/Transcrypt/blob/master/transcrypt/modules/org/transcrypt/compiler.py#L75)

2. that presents various problems when using transcrypt
with various external build systems

3. it would help to have compiler source vs target separation
and expose compiler target root directory as configurable parameter

**Comment by JdeH** [comment]
Yes, indeed this should be in, to achieve more flexibility.

**Comment by JennaSys** [comment]
As of version 3.9.0, Transcrypt now has the `--outdir` [command line parameter](--outdir) that lets you specify the build folder.
