### ISSUE TITLE
How can I catch Javascript exception and print it?

### ISSUE THREAD

**Issue by warrenchopin** [TranscryptOrg/Transcrypt#683]
I encountered an exception thrown during a remote call. It must be thrown inside javascript code because the line "except (Exception, Error)" fails to catch it. Following is the code:
```
try:
    userSession = await self.server.signinExternal(userProfile)
except (Exception, Error) as e: # Not working
    print('Game server: signing in failed.\n'+str(e))
```
If I don't designate the exceptions to  catch (for example, using "except:"), I cannot get the exception as a variable 'e', then I cannot print the exception. I want to catch the javascript exception and print it.  How can I do it?

Thanks in advance.

**Comment by warrenchopin** [comment]
I think that there is a possibility that an exception is not caught in an async call. Is capturing exception in an async call supported in Transcrypt?

**Comment by darthglowball** [comment]
Maybe the bug I encountered will help you. I found that try/except doesn't work correctly when there's an item being indexed in a list. Javascript doesn't error when the item is undefined. Python would error.
```
t=[]
try: t[0]
except: print("error")
```
I used my after-processor on the Javascript to fix that:
```
t=[]
try{ if (!t[0]){throw ''} }
catch { print("error") }
```

**Comment by AlexECX** [comment]
`isinstance(new Error(), Error)` gives false because the first is an object and the second is a function. You can catch anything unsing `object` instead (not `Object` from JS, but the one from transcrypt).

```
try:
    userSession = await self.server.signinExternal(userProfile)
except (object) as e:
    print('Game server: signing in failed.\n'+str(e))
```

**Comment by JennaSys** [comment]
Closing as answered.
