### ISSUE TITLE
Possible to import any packages (scipy, numpy, pandas etc)?

### ISSUE THREAD

**Issue by Zireael** [TranscryptOrg/Transcrypt#684]
Hi, I wanted to use `from scipy.optimize import leastsq` in a simple script I wrote, but I'm getting an error when trying to `transcrypt test.py -b -p .none -n` as follows:

```
Error while compiling (offending file last):
        File '.../server/utilities/misc/python/transcrypt/test.py', line 1, at import of:
        File '.../python3/lib/site-packages/scipy/optimize/__init__.py', line 416, at import of:
        File 'scipy._lib._testutils', line 110, namely:

        Import error, can't find any of:
                .../server/utilities/misc/python/transcrypt/scipy/_lib/_testutils/PytestTester.py
                .../server/utilities/misc/python/transcrypt/scipy/_lib/_testutils/PytestTester.js
```

my test.py only has two lines inside to give it a try:

> from scipy.optimize import leastsq
> print("start")

I was holding slight hope, but my best guess we can convert only pure py and not any of the bigger scientific packages to use in JS?

**Comment by AlexECX** [comment]
See my answer here [#657 Import error with w3lib.encoding (from requests-html)](https://github.com/QQuick/Transcrypt/issues/657#issuecomment-517353271)

**Comment by JdeH** [comment]
Packages like SciPy are written in C/C++.
There are ways to compile C++ into web assembly,
but the result unfortunately is bulky and slow.

**Comment by RAbraham** [comment]
@Zireael Check out https://github.com/iodide-project/pyodide

**Comment by arcman7** [comment]
> Packages like SciPy are written in C/C++.
> There are ways to compile C++ into web assembly,
> but the result unfortunately is bulky and slow.

@JdeH can we not simply import numscrypt and have transcrypt natively support it? Specifically: where any occurrence of the numpy package is encountered, use numscrypt?

**Comment by JennaSys** [comment]
Closing since no further comments.
