### ISSUE TITLE
`time.monotonic` using `performance.now`?

### ISSUE THREAD

**Issue by mentalisttraceur** [TranscryptOrg/Transcrypt#699]
Monotonic clocks are the best practice time source for any code that cares about how much time has passed between moments.

This looks like it would be trivial to add to the `time` module:

```python
def monotonic():
    return performance.now() / 1000
```

Advantage of doing this in Transcrypt's library is that Python code already written to use or prefer `time.monotonic` will just work.

**Comment by mentalisttraceur** [comment]
If I don't hear a "no" maybe I'll just get a PR going once I have time to set up and test it, and we can discuss it in more depth then.

This one should be easier for me to get started on than the other change I suggested months ago.

**Comment by JdeH** [comment]
Sorry this issue has been without an answer for so long.
A contribution to this regard is appreciated!

**Comment by mentalisttraceur** [comment]
@JdeH No problem! I've submitted pull request #765 with it now.

**Comment by JennaSys** [comment]
Implemented in v3.9.2
