### ISSUE TITLE
Use Case of Transcrypt

### ISSUE THREAD

**Issue by GoChartingAdmin** [TranscryptOrg/Transcrypt#703]
Hi,

My use case is to send a code snippet in Python to an api which returns back the JS equivalent of that snippet.

Can we use Transcrypt to achieve this objective. If yes, any guidance on how to get started will be most helpful

PS:  I can use either a backend in nodejs or golang

Regards

**Comment by JdeH** [comment]
The JS snippet would require the runtime of Transcrypt to function.
This has already been done for at least one site in the past.
It entails running Transcrypt on a server to do the compilation.

The steps used for that applicationn were:

- Send sourcecode to server, making a uniquely named folder for it on the fly.
- Compiling as usual, just on the server (which was a Linux machine residing with alwaysdata.com).
- Show eventual error reports.
- Sending back the target code, including the runtime.

In that particular case there was also an on-line editor and the code that got sent back was automatically started in the client browser to see the result, including graphics.

**Comment by JennaSys** [comment]
Closing since no further comments, but will mention that something like this was also brought up on issue #828
