### ISSUE TITLE
2000 * and it's alive

### ISSUE THREAD

**Issue by JdeH** [TranscryptOrg/Transcrypt#717]
**IT'S MOVING AGAIN, SEE COMMENT BELOW, _D.D._ NOV 3 2020**

Dear users and developers of Transcrypt

You haven't heard from me for a long time. Contrary to what you may think, Transcrypt is on my mind most of the days. Due to circumstances with regard to my daytime job, I haven't been able to work on it for a long time, which bothers me a lot.

The Corona crisis adds up to that. Since I am a teacher at the Rotterdam University of Applied Sciences, I am currently occupied day and part of the night with the transfer to on-line education.

But I am really looking forward to returning to Transcrypt development as soon as things calm down a bit. I can't tell exactly when that will be, but it is my sincere intention to stay at it for a long time.

Kind regards and take care of yourself.
Jacques

**Comment by JennaSys** [comment]
Thank you for the reassurance Jacques!  I've only been using Transcrypt for a few months now, but based on my experience so far, Transcrypt is a game changer for Python devs that want to do web UI development. I'm looking forward to future Transcrypt updates.

**Comment by classifaddict** [comment]
Thank you so much Jacques!
I admit that I was a little worried.
Keep up the good work... But in healthcare field first!
We can wait a little more regarding TS.
Take care!
Olivier

**Comment by faerot** [comment]
I hope so. I have a large project where Transcrypt is fundamental part.

**Comment by PhE** [comment]
I tried to get away from Transcrypt by cheating with :
* pyodide (no JS transpilation yet)
* typescript (better than JS but too far from python ease of use)
* nim (nice syntax but limited JS bridging)
But the Transcrypt way is still the best fit each time I need some heavy data science stuff in the browser.

So keep going, we need you !!

**Comment by JdeH** [comment]
Hi all,

I am glad to report that I can once again dedicate a significant fraction of my time to Transcrypt.
I've decided to skip 3.8 (using it internally as a stepping stone) and move directly to a 3.9 release.
From now on I plan to regularly invest time.

First I'd like to get the core in shape for 3.9.
Then I'd like to broaden the effort once again and look around for some additional man/woman-power.
Meanwhile thanks for your patience, all, and also for keeping flowing the issues and PR's.

I've chosen to integrate the PR's once 2.9 is (nearly) ready.
Just want to start adapting to the new syntax of 3.8 and even the new parser of 3.9.
Once that's done, I can breathe a bit more lightly...

KR
Jacques

**Comment by pauleveritt** [comment]
Very good! Once you reach the "broaden the effort" point, please transmit the message and I will propose some things I can do to help on this. Do you think this will be in January, Feb, May, later?

**Comment by alysbrooks** [comment]
This looks like the latest update on the status of this project. Maybe consider pinning it? Regardless, thanks for all your hard work!
