### ISSUE TITLE
string.replace() does not work properly with optional count parameter

### ISSUE THREAD

**Issue by JennaSys** [TranscryptOrg/Transcrypt#722]
If a count parameter is included in replace, it truncates the remaining portion of the string after the last included match.
For example:
```
test = "abcabcabcabc"
test.replace("c", "x", 2)
```
returns: `"abxab"` instead of `"abxabxabcabc"`

The current js implementation is:
```
String.prototype.py_replace = function (old, aNew, maxreplace) {
  return this.split(old, maxreplace).join(aNew);
};
```
The current behavior seems to match the logic of the current implementation.
A possible replacement I came up with that concatenates the remainder of the string is:
```
String.prototype.py_replace = function (old, aNew, maxreplace) {
  return [this.split(old, maxreplace).join(aNew), this.slice(this.split(old, maxreplace).join(old).length + 1)].filter(Boolean).join(aNew);
};
```
There is an edge case with this one that doesn't quite work right if maxreplace=0 (it chops off the 1st character in the string), but does work better than what is there now.

**Comment by AlexECX** [comment]
How about this? It handles `maxreplace=0` the same as if handling `undefined`.

```
String.prototype.py_replace = function (old, aNew, maxreplace) {
  if (maxreplace) {
      return this.split(old, maxreplace).join(aNew) + this.slice(maxreplace);
  } else {
      return this.split(old).join(aNew);
  }
};
```
