### ISSUE TITLE
Where is the 3.9.0 'Berlin' release?

### ISSUE THREAD

**Issue by shawnmasters** [TranscryptOrg/Transcrypt#783]
All of the release information I am tracking is the previous London release and it is not clear if the leading checkout of main is this new version mentioned on the website.

**Comment by Mte90** [comment]
That is from 2018 but the project moved on...

**Comment by shawnmasters** [comment]
Moved on to where?  I see discussion outside of github, but github is stuck in 2018 from a release perspective.  Is there another repo?

**Comment by Mte90** [comment]
I mean the project moved on because there are commits since 2018 the last one is from june.
They just didn't released a new version, so probably the unique way is to use pip with the github repository and not using packages.

**Comment by JennaSys** [comment]
If you `pip install transcrypt` you will get 3.9.0 which btw requires Python 3.9 to work properly (it's tied to the Python AST)

To get the previous version for Python 3.7 use `pip install transcrypt==3.7.16`

**Comment by Mte90** [comment]
Ah ok so they did a release but not on github.

**Comment by JennaSys** [comment]
PyPI and GitHub releases are now in sync.
