### ISSUE TITLE
How to use transcrypt directly in python code

### ISSUE THREAD

**Issue by streetartist** [TranscryptOrg/Transcrypt#791]
I want to use transcrypt in my python code instead of using cmd.how can i do it

**Comment by JennaSys** [comment]
I don't believe Transcrypt s designed to be used as a library where you can import it, but you can run it like any other program using the Python subrocess module:

```
import subprocess
subprocess.run(['transcrypt', 'myapp.py'])
```
That said, depending on your needs, it might make more sense to run it in a shell script instead of a Python file.

**Comment by JennaSys** [comment]
Closing this issue due to no further comments.
