### ISSUE TITLE
Is it possible to generate partial transcripts of python code to javascript, (using strings)?

### ISSUE THREAD

**Issue by JesusZerpa** [TranscryptOrg/Transcrypt#797]
Hello! I would like to thank you for this wonderful project that has worked on transcription from python to javascript, I have been actively using it for some time.

Regarding the question I ask in the title, I need to know if there is any method within the transcrypt code that can be specified or any command in which I pass the string with the python code and that returns a string with the code in javascript, without having to create all the other files

**Comment by JennaSys** [comment]
Transcrypt at this time is intended only to be used as an external tool and does not have an API where it can process in-memory strings. Somewhat similar issues were brought up on #828, #703, and is also kind of related to #622. Those may give some options as to how this problem might be approached.
