### ISSUE TITLE
Good linter to use with Transcrypt?

### ISSUE THREAD

**Issue by halloleo** [TranscryptOrg/Transcrypt#800]
[Following the good example of @JesusZerpa](https://github.com/QQuick/Transcrypt/issues/797) I would like to say thank you for this great project as well. I too am using this tool for a while now.

And I have noticed tgat very often I get runtime  errors for things like miss-spelled varavles or attributes - and as runtime errors I don’t notice them before I execute the script in the browser.

So I thought a linter would solve all of this and give me the errors at compile tine when I edit the code.

**But what is a good linter to use with Transcrypt. And what settings do I need for Javascript FFIs like jQuery or similar?**

**Comment by JennaSys** [comment]
I use PyCharm for most of my coding including Transcrypt type projects.  PyCharm has the capability to introspect both Python and JavaScript, but it's not set up to introspect JavaScript code in py files or Python code in js files.

I have it on my master TODO list to write a plugin that will do that and more (like recognize Transcrypt pragmas) but JetBrains plugins are written in Kotlin, so it's going to be a while before I get around to it.

**Comment by halloleo** [comment]
Good idea to try it in PyCharm. Thanks.
