### ISSUE TITLE
IDE Autocomplete support?

### ISSUE THREAD

**Issue by 4getter** [TranscryptOrg/Transcrypt#801]
I want to use Python instead of JS.

But I'd like to know if Transcrypt has IDE support. Like all the standard IDE features you'd have for Python. Like Autocomplete, error checking etc.

I wouldn't even dream of being able to write code without IDE support.

My assumption that most of the Py to JS solutions don't have IDE support is the only thing holding me back. I hope I'm wrong.

Thanks!

**Comment by JennaSys** [comment]
I know PyCharm does not provide autocomplete for JS in Python files. I'd imagine it can be done with a plug-in, however I do not think one has been created for that purpose yet.  I know I'd certainly welcome a Transcrypt plug-in for PyCharm. I'm not sure about how VSCode handles that.

That said, I usually keep all JS code in one Python module and map JS objects/functions to Python objects/functions within that module.  Then when I import from there, the rest of my Python modules are all pure Python and the IDE does what it is designed to do.
