### ISSUE TITLE
`enumerate` does not obey the `start=` parameter

### ISSUE THREAD

**Issue by halloleo** [TranscryptOrg/Transcrypt#804]
When I run in Transcrypt:

```python
for i, c in enumerate(['a', 'b', 'c'], start=1):
    print(I, c)
```

I get the output:

```
0 a
1 b
2 c
```

while CPython gives me the expected:

```
1 a
2 b
3 c
```

**Comment by JennaSys** [comment]
I just created a PR that adds this argument to the Transcrypt version.

**Comment by halloleo** [comment]
Wow, cool tht this is done!

I guess it is only in in GitHub and not yet in a release, right?

**Comment by JennaSys** [comment]
Correct. I finally got some time to start working on this project again. I'm going to start pulling in some existing PRs and probably release a patch update in a week or so.

**Comment by halloleo** [comment]
Awsome, @JennaSys!
