### ISSUE TITLE
Is this maintained and accepting PRs?

### ISSUE THREAD

**Issue by emirkmo** [TranscryptOrg/Transcrypt#822]
I see several PRs open for 2 years. Is this no longer maintained? Is it accepting PRs? 

The readme and GitHub release don’t have the latest version from Pypi either, so I am confused about what state this library is in.

Also, is any python 3.10 version on the horizon? Will PRs toward that (in a dedicated feature branch?) be accepted?

**Comment by JennaSys** [comment]
I'll be looking at PRs and open issues in the coming months, and plan on a 3.9.1 release with some of the more straightforward updates hopefully in January. This month, [I have been working with Jacques](https://github.com/QQuick/Transcrypt/discussions/836) on getting things in order. And just FYI, the Transcrypt repo will be moving from here (QQuick) to it's new GitHub home at [TranscryptOrg](https://github.com/TranscryptOrg) in the next week or so.

I've already updated the GitHub release to match PyPI, and the README will be updated in the 3.9.1 release.

My plan is to address as many open issues as possible in the coming months, and then likely focus on a 3.11 Python version release (thus skipping 3.10).

Updates may still be a bit slow at first as I dig into this further, but they will be happening. TBH, I'm not looking for more PRs _right_ now as I've already got plenty to dig through, but once the dust has settled a bit, I'll certainly welcome help. I'll be posting in the [discussion area](https://github.com/QQuick/Transcrypt/discussions) as progress is made.

**Comment by JennaSys** [comment]
Well, I ended up getting busy and didn't get anything done on Transcrypt until just now. 3.9.1 has been released, but it's mostly just as an admin task as part of the repo move. But now that the move is done, I can start focusing on some lingering bug fixes.
