### ISSUE TITLE
Help with running online editor with server compilation

### ISSUE THREAD

**Issue by straaljager** [TranscryptOrg/Transcrypt#828]
I would like to create an online computer graphics course with Python, where users can write code in the browser, have it  compiled to Javascript by a server and see the results on a canvas (very similar to the Transcrypt Turtle demo: http://www.transcrypt.org/live/turtle_site/turtle_site.html). 

I'm struggling with setting up a local server to run the Transcrypt compilation and serve the results back to the browser. I could not find anything on this topic in the docs. Is there a minimal example somewhere on how to achieve this?

**Comment by straaljager** [comment]
Thanks a lot @JennaSys. That really helped my understanding of the client-server process. I will try to replicate this behaviour on a local machine.

**Comment by JennaSys** [comment]
Closing since no further comments.
