### ISSUE TITLE
i love the people who made Transcrypt 

### ISSUE THREAD

**Issue by xalteropsx** [TranscryptOrg/Transcrypt#838]
i believe if u can create a discord to further grow community and popularity since unaware alot of people

and i would love to see if people enhance vue3 content in Transcrypt 
since their is composition api and optional api yet i see only optional api 

i wonder why this github not been updated since 2019 

looking forward to working as vue3 developer on transcrypt

**Comment by JennaSys** [comment]
I think a discord could work if there was a bigger audience, but for now the GitHub discussion area has been opened up for general communication. I would be interested in hearing if others have use Transcrypt to create Vue projects.

And rest assured that there will be more updates to Transcrypt forthcoming.
