### ISSUE TITLE
math.copysign() is not a function (missing?)

### ISSUE THREAD

**Issue by chopin** [TranscryptOrg/Transcrypt#867]
Is math.copysign() missing in Transcrypt?

in Python3.9.18:
```
>>> import math
>>> math.copysign(1, 434)
1.0
>>> math.copysign(1, -434)
-1.0

```
Transcrypted:
`
Uncaught TypeError: math.copysign is not a function
`

**Comment by JennaSys** [comment]
Will be included in the next release.
