### ISSUE TITLE
What is the best way to import a library when its type='module'?

### ISSUE THREAD

**Issue by chopin** [TranscryptOrg/Transcrypt#875]
Hi, 

I am trying to import a 3rd party library (Trystero),  This library should be imported by <script type='module'> because it includes 'export' command supported in ES6.

`<script src='trystero-torrent_min.js' type='module>`

A problem is that all variables are not visible outside the module when its type='module'. 

In Transcrypt, what is the best way to import variables from library whose type='module'? (or library using 'export' command supported in ES6?)

I tried to abandon the <script> tag, and  use import from javascript code directly as following:

```
__pragma__('js', '{}', '''
import {joinRoom} from './../trystero-torrent_min.js';
''')
```
It worked, but looks ugly. Moreover, Transcrypt fails to compile from the second compile weirdly. So, I have to remove all the compiled files and recompile all over again. 

Is there a better way to import library in this case? Thanks in advance.

**Comment by JennaSys** [comment]
I mostly do dynamic imports using `require()` because it's clean and almost always just works.  But I'm not sure if that's an option for you.

```python
Trystero = require('trystero')
joinRoom = Trystero.joinRoom
joinRoom()
```

**Comment by chopin** [comment]
> I mostly do dynamic imports using `require()` because it's clean and almost always just works. But I'm not sure if that's an option for you.
> 
> ```python
> Trystero = require('trystero')
> joinRoom = Trystero.joinRoom
> joinRoom()
> ```

Thanks for your response. I tried using require(), but an error was thrown in the browser:

`Uncaught ReferenceError: require is not defined`

In my knowledge, require() is a Node.js function, not Javascript. I think that it cannot be used in Python code for Transcrypt. Is there a way to use it?

**Comment by JennaSys** [comment]
I use the Parcel bundler with the Transcrypt plugin. I makes everything easier without having to get too deep into the JavaScript ecosystem. I did a write-up on [using Parcel v2 with Transcrypt](https://dev.to/jennasys/using-parcel-v2-and-transcrypt-to-create-web-applications-with-python-30ac) a while back. That should give you an idea of how to set it up, but I don't know if fits into your workflow.

**Comment by JennaSys** [comment]
Somewhere in the Transcrypt docs it tells you how to bundle just using the JS rollup library too. It's something like this:

```
npx rollup ./__target__/app.js --o ./__target__/app.bundle.js --f cjs
```

**Comment by JennaSys** [comment]
Did using the `script` tag as above work in your case?

I'm not sure if it impacts the issue, but I also just noticed the braces weren't doubled in the string of your pragma:

```
__pragma__('js', '{}', '''
import {{joinRoom}} from './../trystero-torrent_min.js';
''')
```

**Comment by chopin** [comment]
Yes, using the script tag above worked nicely to me. Also, the compile error from the second trial disappeared too.

Thanks for pointing out the the braces not doubled. They might
have been the cause of the compile error. Anyway the problem solved now. Thanks again.

**Comment by JennaSys** [comment]
> The relevant section of document doesn't mention how to import in case of module type. I hope that this section is updated to include this case [6.1.1. Three ways of integration with JavaScript libraries](https://www.transcrypt.org/docs/html/integration_javascript.html#three-ways-of-integration-with-javascript-libraries)

As suggested, this section of the documentation has been updated.
